name: Evaluate Model (with dataset preview)

on:
  workflow_dispatch: {}

jobs:
  eval:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows committing reports back to repo if desired

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Show workspace & confirm dataset file
        run: |
          echo "Working directory:"
          pwd
          echo "--- TOP LEVEL ---"
          ls -la
          echo "--- Searching for dataset file ---"
          find . -maxdepth 3 -type f -name "amazon_balanced_test.csv" -print
          echo "--- Preview dataset file (raw) ---"
          head -n 20 data/amazon_balanced_test.csv || echo "File not found!"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check dataset statistics before evaluation
        run: |
          python - <<'PY'
          import pandas as pd
          path = "data/amazon_balanced_test.csv"
          df = pd.read_csv(path, quotechar='"', on_bad_lines="skip")
          print(f"✅ Loaded dataset from {path}")
          print(f"Rows: {len(df)}, Columns: {list(df.columns)}")
          print("Class distribution:")
          print(df['sentiment'].value_counts())
          print("\nFirst 5 rows:")
          print(df.head().to_string())
          PY

      - name: Run evaluation (writes to reports/)
        env:
          EVAL_DATA_CSV: data/amazon_balanced_test.csv
          EVAL_TEXT_COL: text
          EVAL_LABEL_COL: sentiment
          EVAL_MODEL_PATH: models/logistic_model.pkl
          EVAL_VECTORIZER_PATH: models/tfidf_vectorizer.pkl
        run: |
          set -euxo pipefail
          mkdir -p reports
          python scripts/evaluate_existing_model.py
          echo "--- reports/ after evaluation ---"
          ls -la reports || true
          echo "--- show generated files ---"
          [ -f reports/metrics_existing.json ] && tail -n +1 reports/metrics_existing.json | head -n 40 || echo "metrics_existing.json MISSING"
          [ -f reports/predictions.csv ] && head -n 10 reports/predictions.csv || echo "predictions.csv MISSING"
          [ -f reports/confusion_matrix_existing.png ] && ls -lh reports/confusion_matrix_existing.png || echo "confusion_matrix_existing.png MISSING"

      - name: Upload reports as artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: reports/
          if-no-files-found: warn

      - name: Commit and push reports
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f reports/* || true
          git commit -m "ci: update evaluation reports" || echo "No changes to commit"
          git push || echo "Nothing to push (maybe no changes)"
