name: Evaluate and Commit

on:
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run evaluation
        run: |
          mkdir -p reports
          python scripts/evaluate_existing_model.py \
            --data_csv data/amazon_balanced_test.csv \
            --text_col text \
            --label_col sentiment \
            --model_path models/logistic_model.pkl \
            --vectorizer_path models/tfidf_vectorizer.pkl

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/*
          git commit -m "ci: add evaluation metrics, confusion matrix and predictions" || echo "No changes to commit"
          git push
