name: Evaluate Model

on:
  workflow_dispatch:   # allows manual trigger from Actions tab

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required so the workflow can push reports to your repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run evaluation
        run: |
          mkdir -p reports
          python scripts/evaluate_existing_model.py
          echo "Reports generated:"
          ls -la reports || true

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: reports/

      - name: Commit reports to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f reports/*
          git commit -m "ci: add evaluation reports" || echo "No changes to commit"
          git push
