name: Evaluate Model

on:
  workflow_dispatch:   # run from the Actions tab

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required so we can push the reports folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run evaluation (writes to reports/)
        run: |
          mkdir -p reports
          python scripts/evaluate_existing_model.py
          echo "Reports generated:" && ls -la reports || true

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: reports/
          if-no-files-found: error

      - name: Commit reports to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f reports/*
          git commit -m "ci: add evaluation reports" || echo "No changes to commit"
          git push
