name: Evaluate and Commit
on: { workflow_dispatch: {} }

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run evaluation (writes to reports/)
        env:
          # Optional overrides if your CSV headers differ:
          # EVAL_DATA_CSV: data/amazon_balanced_test.csv
          # EVAL_TEXT_COL: text
          # EVAL_LABEL_COL: sentiment
          # EVAL_MODEL_PATH: models/logistic_model.pkl
          # EVAL_VECTORIZER_PATH: models/tfidf_vectorizer.pkl
        run: |
          python scripts/evaluate_existing_model.py
          echo "Listing reports/"
          ls -la reports || true

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/* || true
          git commit -m "ci: add evaluation metrics, confusion matrix and predictions" || echo "No changes to commit"
          git push
