name: Evaluate (Manual, Artifact)

on:
  workflow_dispatch: {}

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          mkdir -p reports
          python scripts/evaluate_existing_model.py \
            --model-path models/logistic_model.pkl \
            --vectorizer-path models/tfidf_vectorizer.pkl \
            --data-csv data/amazon_balanced_test.csv \
            --text-col text \
            --label-col sentiment \
            --metrics-out reports/metrics_existing.json \
            --cm-out reports/confusion_matrix_existing.png
          python scripts/predict_existing_model.py \
            --model-path models/logistic_model.pkl \
            --vectorizer-path models/tfidf_vectorizer.pkl \
            --input-csv data/amazon_balanced_test.csv \
            --text-col text \
            --output-csv reports/predictions.csv
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: |
            reports/metrics_existing.json
            reports/confusion_matrix_existing.png
            reports/predictions.csv
          if-no-files-found: error
